---
- name: Install soft & upload web page
  hosts: all
  become: yes
  vars:
    source: https://github.com/Kowalsky89/ansible/index.html
    destination: /var/www
  tasks:
  - name: Install soft
    apt: name=nginx state=latest
    apt: name=zsh state=latest
    apt: name=wget state=latest
  - name: Get web page
    get_url: url={{source}} dest={{destination}}
    notify: Restart nginx
  - name: Start nginx & make it enabled on boot
    service: name=nginx state=started enabled=yes
  handlers:
  - name: Restart nginx
    service: name=nginx state=restarted
